name: pytorch-env
channels:
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - cuda-toolkit
  - cudnn
  - datasets
  - diffusers
  - transformers
